# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
# allow workflow dispatch
on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      
    env:
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      

      - name: Run establish a ngrok tunnel
        id: test
        uses: vmactions/ngrok-tunnel@v0.0.1
        with:
          protocol: http
          port: 8080

      - name: write output from step "test" to file
        id: write-output
        uses: DamianReeves/write-file-action@master
        with:
        path: $GITHUB_WORKSPACE/ngrok.url
        contents: |
        ${{ steps.test.outputs.server }}
       write-mode: overwrite
        run: |
          git config --global user.email "sus@sus.sus"
          git config --global user.name "end-me-bot"
          git add ngrok.url
          git commit -m "Add ngrok.url"
          git push

      



      - name: Run the script
        run: |
          npm i express
          npm i socket.io
          node index.js