# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
# allow workflow dispatch
on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      
    env:
      NGROK_TOKEN : ${{ secrets.NGROK_TOKEN }}

    steps:
    - name: Run establish a ngrok tunnel
        id: test
        uses: vmactions/ngrok-tunnel@v0.0.1
        with:
          protocol: http
          port: 8800
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node index.js


